---
title: "Figure Building"
output: html_notebook
---


```{r}
library(dplyr)
library(lubridate)
library(rnaturalearth)
library(sf)
library(ggplot2)
library(zoo)
```


```{r}
dat<- read.csv("LWKs-2019-12-19.csv")

data <- dat %>% 
  select("Data.Resource.Name", 
       "Locality", 
       "Latitude", 
       "Longitude",
       "IBRA.7.Regions",
       "Individual.count", 
       "Year", 
       "Month", 
       "Day", 
       "Event.Date...parsed"
       ) %>% 
  dplyr::filter(!is.na(Latitude)) %>% 
  mutate(Year<=2010) %>% 
  rename("New"='Year <= 2010') %>% 
  dplyr::filter(!is.na(New))

fence <- sf::st_read("data/DingoFenceGoodGoodSA.shp")

lwk_points <- st_as_sf(data, coords=c("Longitude", "Latitude"), crs=st_crs(fence))

sites <- read.csv("data/Sites.csv", header = TRUE)

site_points <- st_as_sf(sites, coords=c("Lon", "Lat"), crs=st_crs(fence))

Aus<- st_read("data/1259030001_ste11aaust_shape/STE11aAust.shp")

```

```{r}
map <- ggplot()+
  geom_sf(data=Aus)+
  geom_sf(data=fence, size = 0.5, colour = "Red")+
  geom_sf(data=lwk_points, size=1, aes(colour = data$New))+
  geom_sf(data=site_points, size=2, colour = "Black")+
  xlim(137, 145)+
  ylim(32, 27)+
  coord_sf() +
  theme_bw() +
  ggtitle("Letter-winged Kite Sightings")+ 
  theme(legend.title = element_blank()) +
  scale_fill_manual(values = c('Blue', 'Red'),
                    labels = c('Points', 'Fire'))

print(map)
```

#Make rodent line graphs
```{r}
traps<- read.csv("data/rodent_data.csv")
traps <- na_if(traps, "#NULL!")
traps$fuscusperhundred <- as.numeric(traps$fuscusperhundred)
traps$Trip<-dmy(traps$Trip)

traps$Rattusperhundred <- as.numeric(traps$Rattusperhundred)
traps$Smac <- as.numeric(traps$Smac)
traps$Scrassi <- as.numeric(traps$Scrassi)
traps$Mus <- as.numeric(traps$Mus)
traps$Paustralis <- as.numeric(traps$Paustralis)
traps$Pherman <- as.numeric(traps$Pherman)
traps$Pdesertor <- as.numeric(traps$Pdesertor)



ggplot(traps, aes(Trip, fuscusperhundred)) +
  geom_line(aes(colour = fence))
ggplot(traps, aes(Trip, fuscusperhundred)) +
  geom_line(aes(colour = site))


```

#Averaging sites by fence
```{r}
inside<- filter(traps, fence == "in")
outside<- filter(traps, fence == "out")

outsidenew <- outside %>% 
  dplyr::group_by(Trip) %>% 
  mutate("Notomys fuscus" = mean(fuscusperhundred, na.rm=TRUE)) %>%
  mutate("Leggadina foresti" = mean(leggadina, na.rm=TRUE)) %>%
  mutate("Rattus villosissimus" = mean(Rattusperhundred, na.rm=TRUE)) %>%
  mutate("Sminthopsis macroura" = mean(Smac, na.rm=TRUE)) %>%
  mutate("Sminthopsis crassicaudata" = mean(Scrassi, na.rm=TRUE)) %>%
  mutate("Mus musculus" = mean(Mus, na.rm=TRUE)) %>%
  mutate("Pseudomys australis" = mean(Paustralis, na.rm=TRUE)) %>%
  mutate("Pseudomys hermannsburgensis" = mean(Pherman, na.rm=TRUE)) %>%
  mutate("Pseudomys desertor" = mean(Pdesertor, na.rm=TRUE)) %>%
  mutate("Dasycercus cristicauda" = mean(mulgara, na.rm=TRUE)) %>%
  dplyr::ungroup(Trip)

insidenew <- inside %>% 
  dplyr::group_by(Trip) %>% 
  mutate("Notomys fuscus" = mean(fuscusperhundred, na.rm=TRUE)) %>%
  mutate("Leggadina foresti" = mean(leggadina, na.rm=TRUE)) %>%
  mutate("Rattus villosissimus" = mean(Rattusperhundred, na.rm=TRUE)) %>%
  mutate("Sminthopsis macroura" = mean(Smac, na.rm=TRUE)) %>%
  mutate("Sminthopsis crassicaudata" = mean(Scrassi, na.rm=TRUE)) %>%
  mutate("Mus musculus" = mean(Mus, na.rm=TRUE)) %>%
  mutate("Pseudomys australis" = mean(Paustralis, na.rm=TRUE)) %>%
  mutate("Pseudomys hermannsburgensis" = mean(Pherman, na.rm=TRUE)) %>%
  mutate("Pseudomys desertor" = mean(Pdesertor, na.rm=TRUE)) %>%
  mutate("Dasycercus cristicauda" = mean(mulgara, na.rm=TRUE)) %>%
  dplyr::ungroup(Trip)

trapsnew<- bind_rows(insidenew, outsidenew)

trapsfin <- trapsnew %>% 
  select(-"site", -"leggadina", -"Rattusperhundred", -"fuscusperhundred", -"Smac", -"Scrassi", -"Mus", -"Paustralis", -"Pherman", -"Pdesertor", -"daysuridspecies", -"rodentspecies", -"mulgara", -"letterwingselect", -"letterwingperkm") %>% 
  tidyr::gather(Species, Capsphund, "Notomys fuscus":"Dasycercus cristicauda") %>% 
  distinct()

infin <- filter(trapsfin, fence == "in")
outfin <- filter(trapsfin, fence == "out")
```

#label trick
```{r}
label.df <- data.frame(Trip = c("1-Jul-2013", "1-Mar-2014", "1-Jul-2015", "1-Nov-2017", "1-Mar-2018"),
                       Capsphund = c(75), 
                       Species = NA)

label.df$Trip<-dmy(label.df$Trip)

```

#Making Plots
```{r}
inplot<- ggplot(infin, aes(Trip, Capsphund, fill = Species)) +
  geom_col(aes(position = "stack")) + 
  theme_bw() + ggtitle("Dingo Rare") + 
  xlab("Sampling Trip") + 
  ylab("Captures per 100 Trap Nights") +
  scale_y_continuous(limits = c(0, 100), expand = c(0,0)) + 
  theme(legend.text = element_text(face = "italic"))

outplot<- ggplot(outfin, aes(Trip, Capsphund, fill = Species)) +
  geom_col(aes(position = "stack")) + 
  theme_bw() + ggtitle("Dingo Common") + 
  xlab("Sampling Trip") + 
  ylab("Captures per 100 Trap Nights") +
  scale_y_continuous(limits = c(0, 100), expand = c(0,0)) + 
  theme(legend.text = element_text(face = "italic")) +
  geom_text(data = label.df, label = "*")

print(inplot)
print(outplot)

```

#Lwk presence
```{r}
lwk<- read.csv("lwkpresence.csv")
lwk$Year<- as.character(lwk$Year)
ggplot(lwk, aes(Year, Present)) + geom_col()
```
#Rainfall
```{r}
rain1<- read.csv("Data/lindonrain/IDCJAC0001_017115_Data1.csv")

rain1$Date <- as.yearmon(paste(rain1$Year, rain1$Month), "%Y %m")

#label.df <- data.frame(Year = c(2013, 2014, 2015, 2017, 2018),
#                       Month = c(7, 3, 6, 11, 3),
#                       Monthly.Precipitation.Total..millimetres. = c(20, 55, 20, 23, 20))

#label.df$Date <- as.yearmon(paste(label.df$Year, label.df$Month), "%Y %m")


rainset<- filter(rain1, Year >= 2011)
ggplot(rainset, aes(x = Date, y = Monthly.Precipitation.Total..millimetres.)) + 
  geom_col() + 
  theme_bw() +
  xlab("Time") +
  ylab("Monthly Precipitation in Millimetres")
#+
#  geom_text(data = label.df, label = "*")

```

